ldadmin.jsonld_mapping.*:
  type: config_entity
  label: 'JSON-LD Mapping config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Description'
    nid:
      type: string
      label: 'NID'
    json:
      type: text
      label: 'JSON-LD'
    uuid:
      type: string
